name: Release on GitHub & PyPI

on:
  push:
    tags:
      - "v*"

env:
  CMEEL_LOG_LEVEL: DEBUG

jobs:
  build:
    name: "${{ matrix.build }} ${{ matrix.os }} ${{ matrix.arch }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        arch: ["x86_64", "aarch64"]
        build: ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "pp38-*", "pp39-*", "pp310-*"]
        exclude:
          - os: "macos-latest"
            build: "cp38-*"
          - os: "macos-latest"
            arch: "aarch64"
          - arch: "aarch64"
            build: "pp38-*"
          - arch: "aarch64"
            build: "pp39-*"
          - arch: "aarch64"
            build: "pp310-*"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - run: pipx install cibuildwheel
      - run: cibuildwheel --output-dir wh
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_MANYLINUX_AARCH64_IMAGE: "quay.io/pypa/manylinux_2_28_aarch64"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_ENVIRONMENT: CMEEL_LOG_LEVEL="DEBUG"
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  release:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: pipx install twine
      - run: twine upload -u __token__ -p "${{ secrets.PYPI_TOKEN }}" artifact/cmeel_boost*.whl
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG}}" "${{ env.TAG }}" artifact/cmeel_boost*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
